# Use Node.js LTS version as the base image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose the port your app will run on
EXPOSE 8080

# Command to run the application
CMD ["npm", "run", "start:prod"]a
